import { useState, type ReactNode } from 'react';
import { ArrowRight, MapPin, Phone, Mail, LockKeyhole, LocateFixed, Truck, Clock3 } from 'lucide-react';
import { RouteMap } from '../components/RouteMap';
import { PrivacyPage } from '../components/PrivacyPage';
import { QuoteForm } from './QuoteForm';
import { directoryPages, distanceKm, fleet, localities, nearbyPlaces, PAGE_SIZE, perth, postcodes, services, type Locality, type PageInfo } from './catalog';

export function PageHero({ page, eyebrow, children }: { page: PageInfo; eyebrow?: string; children?: ReactNode }) {
  return <section className="pageHero"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span>{page.place ? <><a href="/locations">Locations</a><span>/</span></> : page.postcode ? <><a href="/postcodes">Postcodes</a><span>/</span></> : page.service ? <><a href="/freight">Freight</a><span>/</span></> : null}<span aria-current="page">{page.place?.name || page.postcode || page.service?.name || page.path.split('/')[1].replace(/-/g, ' ')}</span></nav><span className="eyebrow">{eyebrow || 'Transline Logistics / Western Australia'}</span><h1>{page.heading}</h1><p>{page.description}</p>{children}</section>;
}
export function ContactStrip() { return <section className="contactStrip"><div><span className="eyebrow">Plan the next move</span><h2>Start with dispatch.</h2></div><a className="button button--primary" href="/quote">Request a quote <ArrowRight /></a><a className="textLink" href="tel:+61466582734"><Phone />0466 582 734</a></section>; }
function ServiceCards() { return <div className="serviceGrid">{services.map((item, i) => <a className="serviceItem" href={`/freight/${item.slug}`} key={item.slug}><div className="serviceItem__top"><span>0{i + 1}</span><ArrowRight /></div><h3>{item.name}</h3><strong>{item.tag}</strong><p>{item.body}</p></a>)}</div>; }
function PlanningChecklist({ locality }: { locality?: string }) { return <div className="planningChecklist"><h2>Before you book{locality ? ` in ${locality}` : ''}</h2><ol><li><strong>Confirm both addresses.</strong><p>A postcode can cover several places. Include the street, suburb, postcode and a contact at each end.</p></li><li><strong>Describe the whole load.</strong><p>List quantities, dimensions, total weight and anything fragile or irregular.</p></li><li><strong>Check loading access.</strong><p>Confirm truck access, parking, stairs or lifts, and whether a forklift or other unloading assistance is available.</p></li><li><strong>Agree the window.</strong><p>Dispatch checks availability and confirms the vehicle and timing before accepting the booking.</p></li></ol></div>; }
function PlaceLinks({ places, distances = false }: { places: (Locality & { distance?: number })[]; distances?: boolean }) { return <ul className="placeLinks">{places.map(place => <li key={place.id}><a href={`/locations/${place.id}`}><span>{place.name}<small>WA {place.postcode}{distances ? ` · approx. ${place.distance} km away` : ''}</small></span><ArrowRight /></a></li>)}</ul>; }
function SourceNote() { return <p className="sourceNote">Locality and postcode reference: <a href="https://www.geonames.org/postal-codes/" target="_blank" rel="noreferrer">GeoNames</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Coordinates are approximate locality reference points. Confirm the street address and service availability with dispatch.</p>; }

function Directory({ page }: { page: PageInfo }) {
  const [query, setQuery] = useState('');
  const current = page.page || 1;
  const result = query.trim() ? localities.filter(place => `${place.name} ${place.postcode}`.toLowerCase().includes(query.trim().toLowerCase())).slice(0, 100) : localities.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);
  return <><PageHero page={page} eyebrow="WA / Towns, suburbs + postcode reference" /><section className="directorySection contentShell"><div className="directoryTools"><label htmlFor="place-search">Find a town, suburb or postcode<input id="place-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Try Welshpool or 6106" /></label><a className="textLink" href="/postcodes">Browse by postcode <ArrowRight /></a></div><p className="directoryCount">{query ? `${result.length} matching locations${result.length === 100 ? ' (first 100 shown)' : ''}` : `${localities.length.toLocaleString('en-AU')} location records · Page ${current} of ${directoryPages}`}</p><PlaceLinks places={result} />{!result.length && <p role="status">No locations match. Try a shorter name or postcode.</p>}{!query && <nav className="pagination" aria-label="Directory pages">{Array.from({ length: directoryPages }, (_, i) => <a key={i} href={i === 0 ? '/locations' : `/locations/page/${i + 1}`} aria-current={current === i + 1 ? 'page' : undefined}>{i + 1}</a>)}</nav>}<SourceNote /></section></>;
}

function LocalityPage({ page }: { page: PageInfo }) {
  const place = page.place!; const nearby = nearbyPlaces(place); const distance = distanceKm(perth, place);
  const sameCode = localities.filter(item => item.postcode === place.postcode && item.id !== place.id);
  return <><PageHero page={page} eyebrow={`Location guide / Western Australia / ${place.postcode}`}><a className="button button--primary" href="#enquiry">Plan a job in {place.name} <ArrowRight /></a></PageHero><section className="localityOverview contentShell"><div><span className="eyebrow">Location reference</span><h2>{place.name}, WA {place.postcode}</h2><p>{place.name} is listed in Western Australia under postcode <a href={`/postcodes/${place.postcode}`}>{place.postcode}</a>. Its reference point is approximately {distance} km in a straight line from central Perth.</p><p>Use the locality and postcode together when describing your pickup or destination. Road distance, access and timing depend on the exact addresses and are confirmed by dispatch.</p><dl className="locationFacts"><div><dt>Postcode</dt><dd><a href={`/postcodes/${place.postcode}`}>{place.postcode}</a></dd></div><div><dt>Approx. latitude</dt><dd>{place.lat.toFixed(4)}°</dd></div><div><dt>Approx. longitude</dt><dd>{place.lng.toFixed(4)}°</dd></div><div><dt>From central Perth</dt><dd>~{distance} km <small>straight line</small></dd></div></dl><a className="textLink" href={`https://www.openstreetmap.org/?mlat=${place.lat}&mlon=${place.lng}#map=12/${place.lat}/${place.lng}`} target="_blank" rel="noreferrer">View locality street map <ArrowRight /></a></div><RouteMap variant="tracking" theme="light" referencePoint={{ locality: place.name, latitude: place.lat, longitude: place.lng }} /></section><section className="contentShell localPlanning"><PlanningChecklist locality={place.name} /><div><span className="eyebrow">Nearby locality reference points</span><h2>Around {place.name}</h2><PlaceLinks places={nearby} distances /><p className="sourceNote">Distances are approximate straight-line measurements, not driving distances or transit estimates.</p></div></section>{sameCode.length > 0 && <section className="contentShell samePostcode"><h2>Also listed in {place.postcode}</h2><PlaceLinks places={sameCode.slice(0, 12)} /><a className="textLink" href={`/postcodes/${place.postcode}`}>All locations in {place.postcode} <ArrowRight /></a></section>}<section className="contentShell enquirySection" id="enquiry"><div><span className="eyebrow">Send dispatch the details</span><h2>A job in<br />{place.name}?</h2><p>Availability is checked for the exact load and addresses. This directory entry is a location reference and does not indicate a past delivery or guaranteed service.</p><div className="serviceChips">{services.map(item => <a href={`/freight/${item.slug}`} key={item.slug}>{item.name} ↗</a>)}</div></div><QuoteForm destination={`${place.name} WA ${place.postcode}`} /></section><div className="contentShell"><SourceNote /></div></>;
}

function PostcodePage({ page }: { page: PageInfo }) {
  const places = localities.filter(place => place.postcode === page.postcode); const names = places.slice(0, 4).map(place => place.name).join(', ');
  return <><PageHero page={page} eyebrow="Western Australia / Postcode reference" /><section className="contentShell postcodeIntro"><h2>{places.length} listed {places.length === 1 ? 'location' : 'locations'} in {page.postcode}</h2><p>Postcode {page.postcode} includes {names}{places.length > 4 ? ' and other listed localities' : ''}. Select the town or suburb to see its approximate map position, nearby places and booking preparation.</p><p>Always include the locality name and full street address. A shared postcode does not mean that all addresses have the same access, distance or delivery availability.</p><PlaceLinks places={places} /><SourceNote /></section><section className="contentShell localPlanning"><PlanningChecklist /><div><h2>Other WA postcodes</h2><div className="postcodeGrid">{postcodes.filter(code => code !== page.postcode).sort((a,b) => Math.abs(Number(a) - Number(page.postcode)) - Math.abs(Number(b) - Number(page.postcode))).slice(0, 12).map(code => <a key={code} href={`/postcodes/${code}`}>WA {code} <ArrowRight /></a>)}</div><a className="textLink" href="/postcodes">All WA postcodes <ArrowRight /></a></div></section><ContactStrip /></>;
}

export function Pages({ page }: { page: PageInfo }) {
  if (page.kind === 'directory') return <Directory page={page} />;
  if (page.kind === 'locality') return <LocalityPage page={page} />;
  if (page.kind === 'postcode') return <PostcodePage page={page} />;
  if (page.kind === 'privacy') return <div className="legacyPage"><PrivacyPage /></div>;
  return <><PageHero page={page} />
    {page.kind === 'freight' && <><section className="contentShell"><ServiceCards /></section><section className="contentShell localPlanning"><PlanningChecklist /><div><h2>One call.<br />A clear starting point.</h2><p>A cargo van and a flatbed solve different jobs. Send the measurements and site conditions first so dispatch can assess the right option.</p><a className="textLink" href="/fleet">Explore vehicle types <ArrowRight /></a></div></section></>}
    {page.kind === 'service' && <><section className="contentShell localPlanning"><div><span className="eyebrow">What to send dispatch</span><h2>{page.service!.tag}</h2><ul className="detailList">{page.service!.details.map(detail => <li key={detail}>{detail}</li>)}</ul><p>{page.service!.fit}</p><a className="textLink" href="/fleet">View fleet options <ArrowRight /></a></div><PlanningChecklist /></section><section className="contentShell enquirySection"><div><h2>Let’s plan<br />your {page.service!.name.toLowerCase()}.</h2><p>Give dispatch the details to assess capacity, availability and timing.</p></div><QuoteForm /></section></>}
    {page.kind === 'coverage' && <section className="contentShell coveragePage"><RouteMap variant="tracking" theme="light" /><div className="coveragePage__notes"><div><span className="eyebrow">Past delivery points</span><h2>A record of the work.</h2><p>Past delivery points are shown at town or suburb level. Customer addresses and live driver positions are kept private.</p></div><div><span className="eyebrow">Planning a new job?</span><p>Send the exact pickup and delivery locations to dispatch. Each job is checked for vehicle availability, load suitability and access.</p><a className="textLink" href="/locations">Search the WA directory <ArrowRight /></a></div></div></section>}
    {page.kind === 'fleet' && <section className="contentShell fleetPage">{fleet.map(item => <article className="fleetSpec" key={item.name}><span className="eyebrow">{item.tag}</span><h2>{item.name}</h2><Truck aria-hidden="true" /><p>{item.body}</p><ul>{item.points.map(point => <li key={point}>{point}</li>)}</ul></article>)}<p className="sourceNote">Exact payload, dimensions and availability vary by vehicle. Dispatch confirms the specification before booking.</p></section>}
    {page.kind === 'tracking' && <section className="contentShell trackingPage"><div className="trackingPanel"><LockKeyhole /><h2>Admin access.</h2><p>Authorised Transline staff can open the operations portal to view drivers, vehicles and shift activity.</p><a className="button button--primary" href="/portal/login">Open admin portal <ArrowRight /></a></div><div className="trackingFeatures">{[{ Icon: LocateFixed, title: 'Driver locations', body: 'See the latest reported GPS position in the live map.' }, { Icon: Truck, title: 'Vehicle assignments', body: 'Keep the driver and assigned vehicle connected.' }, { Icon: Clock3, title: 'Shifts + history', body: 'Review active shifts and recorded route history.' }].map(({Icon, title, body}) => <div key={title}><Icon /><h3>{title}</h3><p>{body}</p></div>)}<p>Need an update on your delivery? <a href="/contact">Contact dispatch</a>.</p></div></section>}
    {page.kind === 'about' && <><section className="contentShell aboutEditorial"><span className="editorialWord" aria-hidden="true">TL.</span><div><h2>Close to the work.<br />Clear on the details.</h2><p>Transline Logistics operates from Perth with a company-owned fleet spanning cargo vans, flatbeds, curtainsiders and pantechs.</p><p>We handle freight, courier and removals enquiries through one dispatch contact. Every job starts with the same practical questions: what is the load, where is it going and what access is available?</p><a className="textLink" href="/contact">Speak with the team <ArrowRight /></a></div></section><section className="contentShell principlesGrid">{[['The load comes first.', 'Dimensions, weight and handling requirements shape the vehicle choice.'], ['Access is part of the job.', 'Loading and unloading arrangements are agreed before dispatch.'], ['Keep the contact direct.', 'Speak to dispatch about your booking, timing or delivery enquiry.']].map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</section></>}
    {page.kind === 'contact' && <section className="contentShell contactPage"><a href="tel:+61466582734"><Phone /><span>Call dispatch</span><strong>0466 582 734</strong><ArrowRight /></a><a href="mailto:admin@translinelogistics.org"><Mail /><span>Email the team</span><strong>admin@translinelogistics.org</strong><ArrowRight /></a><div><MapPin /><span>Operations base</span><strong>Perth, Western Australia</strong></div><p>For a quote, have your pickup, destination, load dimensions and preferred window ready. For an existing delivery, include the booking details so dispatch can locate the job.</p></section>}
    {page.kind === 'quote' && <section className="contentShell enquirySection"><div><h2>Enough detail<br />to get moving.</h2><p>Prepare your enquiry here, then send it through your email app. For an urgent enquiry, call dispatch directly.</p><a className="textLink" href="tel:+61466582734"><Phone />0466 582 734</a></div><QuoteForm /></section>}
    {page.kind === 'postcodes' && <section className="contentShell"><p className="directoryCount">{postcodes.length} WA postcode groups</p><div className="postcodeGrid">{postcodes.map(code => <a key={code} href={`/postcodes/${code}`}><span>{code}<small>{localities.filter(place => place.postcode === code).length} listed locations</small></span><ArrowRight /></a>)}</div><SourceNote /></section>}
    {page.kind === 'notfound' && <section className="contentShell notFound"><p>The address may have changed. Find your next destination below.</p><a className="button button--primary" href="/">Back to home <ArrowRight /></a><a className="textLink" href="/locations">Find a location <ArrowRight /></a></section>}
    {!['quote', 'notfound', 'service', 'tracking'].includes(page.kind) && <ContactStrip />}
  </>;
}
